on: [workflow_dispatch]

name: Release

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: true
      matrix:
        os: [windows-latest, macos-latest]
        build_type: [release]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --${{ matrix.build_type }}
      - name: Check
        run: cargo check --all-features

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: target/${{ matrix.build_type }}/tes3map${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          if-no-files-found: error
